Navbar
ScribeDAO/scribedao.github.io pull request #16
Opened 2021-10-04 00:25 UTC by campbellkearns

- adds navbar for md+ breakpoints
- adds nested mobile navbar
- made one change to font defaults in Tailwind config for pixel precision

I'm glad we chose Tailwind, this was my first time using it. I'm open to all changes.

2021-10-04 00:27 UTC, saihaj commented
![image](https://user-images.githubusercontent.com/44710980/135778687-153bd561-b2fc-470a-901a-35ecb2589b1f.png)

2021-10-04 00:40 UTC, campbellkearns commented
whoops! cool didn't realize we added these linter checks - very helpful

2021-10-04 00:44 UTC, campbellkearns commented
also, the navbar definitely needs to be distilled into more reusable components but for now everything is there in that one component

2021-10-04 01:00 UTC, saihaj requested changes
great work! For now should be fine but we can refactor just create an issue so we have it there. Hover color on nav items is little hard to tell so need to change it.

2021-10-04 01:01 UTC, saihaj commented on src/components/navbar.tsx
> +                src="/static/logo_footer.png"
@shubham15014

2021-10-04 01:09 UTC, saihaj commented
test

2021-10-04 01:12 UTC, campbellkearns commented on src/components/navbar.tsx
> +function Nav() {
Cool, pushing this export change now. Tomorrow I'll add custom colors to the config 🚀

2021-10-05 19:26 UTC, saihaj approved these changes
🚀

2021-10-05 19:27 UTC, merged